/**
 * Clean crusader spritesheet layout.
 *
 * Source: public/assets/crusade/crusader-clean.png — generated by
 * `npm run sprites:slice` from the labeled reference art. It is a 1024×512 sheet
 * of 256px transparent cells, 4 columns × 2 rows, every knight centered on its
 * body and bottom-aligned to a shared feet baseline.
 *
 * Row 0 — Idle loop (4 frames, breathing)
 * Row 1 — Attack sequence (4 frames; the final frame bridges back to idle)
 */

export const CRUSADER_SPRITE_SHEET = '/assets/crusade/crusader-clean.png';

/** Source pixel size of each cell in the clean sheet */
export const SOURCE_FRAME_SIZE = 256;

/** Canvas backing-store size — rendered 1:1 with the source cell for crisp art */
export const DISPLAY_FRAME_SIZE = 256;

/** Default on-screen size (CSS px) of the sprite */
export const DISPLAY_SIZE = 128;

export const SHEET_COLS = 4;

/** @typedef {{ col: number, row: number }} SpriteCell */

/** @type {SpriteCell[]} */
export const IDLE_LOOP = [
  { col: 0, row: 0 },
  { col: 1, row: 0 },
  { col: 2, row: 0 },
  { col: 3, row: 0 },
];

/** @type {SpriteCell[]} */
export const ATTACK_LOOP = [
  { col: 0, row: 1 },
  { col: 1, row: 1 },
  { col: 2, row: 1 },
  { col: 3, row: 1 },
];

/** Final attack frame — hold briefly before resuming idle */
export const ATTACK_BRIDGE_INDEX = 3;

export const IDLE_RESTART_INDEX = 0;

export const ANIM_TIMING = {
  idleFrameMs: 200,
  attackFrameMs: 95,
  bridgeHoldMs: 240,
};

/**
 * Per-frame idle durations (ms). Holding the "rest" extremes longer than the
 * transition frames gives the breathing an ease-in/ease-out feel instead of a
 * mechanical metronome tick. Falls back to ANIM_TIMING.idleFrameMs if missing.
 * @type {number[]}
 */
export const IDLE_FRAME_MS = [340, 170, 340, 170];

/**
 * Draw a single sprite cell, cleared, into the destination square.
 * @param {CanvasRenderingContext2D} ctx
 * @param {HTMLImageElement} image
 * @param {SpriteCell} cell
 * @param {number} destSize
 */
export function drawSpriteCell(ctx, image, cell, destSize = DISPLAY_FRAME_SIZE) {
  const sx = cell.col * SOURCE_FRAME_SIZE;
  const sy = cell.row * SOURCE_FRAME_SIZE;

  ctx.imageSmoothingEnabled = true;
  ctx.imageSmoothingQuality = 'high';
  ctx.clearRect(0, 0, destSize, destSize);
  ctx.drawImage(
    image,
    sx,
    sy,
    SOURCE_FRAME_SIZE,
    SOURCE_FRAME_SIZE,
    0,
    0,
    destSize,
    destSize
  );
}
